-- Database: calculator_db

-- DROP DATABASE IF EXISTS calculator_db;

CREATE DATABASE calculator_db
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1251'
    LC_CTYPE = 'English_United States.1251'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
-- DROP TABLE IF EXISTS expression;

CREATE TABLE expression (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term varchar(300) NOT NULL,
    answer varchar(200) NOT NULL
);

INSERT INTO expression (term, answer) VALUES
                                         ('(2+2)*2', '8.0'),
                                         ('0.25*4', '1.0'),
                                         ('0.7+0.125', '0.825');